#!/bin/bash

    # Creates the systemd service file
    cat << EOF > /etc/systemd/system/prebuild.service
[Unit]
Description=Prebuild – Spawn Project
After=network.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c "\
  rm /etc/network/interfaces; \
  ip link set ens3 up; \
  ip addr add 10.0.12.249/24 dev ens3; \
  ip route add default via 10.0.12.254 dev ens3; \
  sed -i '/^PermitRootLogin/d' /etc/ssh/sshd_config; \
  sed -i '/^PermitEmptyPasswords/d' /etc/ssh/sshd_config; \
  echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config; \
  echo 'PermitEmptyPasswords yes' >> /etc/ssh/sshd_config; \
  systemctl try-restart sshd; \
  passwd -d root"
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload && systemctl enable kernel-cleanup.service --quiet




